// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACxM6Bt_EsolxXJAtSKgYd4cqLOjFeVKg',
    appId: '1:776989325391:web:f993912938eeebed6cd23a',
    messagingSenderId: '776989325391',
    projectId: 'ayucarefinalpro',
    authDomain: 'ayucarefinalpro.firebaseapp.com',
    storageBucket: 'ayucarefinalpro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACowZ68ppqPnInH-bhiWsCXy71UW5sknI',
    appId: '1:776989325391:android:2a633e84687cd0a36cd23a',
    messagingSenderId: '776989325391',
    projectId: 'ayucarefinalpro',
    storageBucket: 'ayucarefinalpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFJx-QYRVCRu9b6JMylsvJVHqcLdTso5g',
    appId: '1:776989325391:ios:d7437a53ae047ffa6cd23a',
    messagingSenderId: '776989325391',
    projectId: 'ayucarefinalpro',
    storageBucket: 'ayucarefinalpro.appspot.com',
    iosBundleId: 'com.example.ayurcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFJx-QYRVCRu9b6JMylsvJVHqcLdTso5g',
    appId: '1:776989325391:ios:d7437a53ae047ffa6cd23a',
    messagingSenderId: '776989325391',
    projectId: 'ayucarefinalpro',
    storageBucket: 'ayucarefinalpro.appspot.com',
    iosBundleId: 'com.example.ayurcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACxM6Bt_EsolxXJAtSKgYd4cqLOjFeVKg',
    appId: '1:776989325391:web:23c8796206766ca96cd23a',
    messagingSenderId: '776989325391',
    projectId: 'ayucarefinalpro',
    authDomain: 'ayucarefinalpro.firebaseapp.com',
    storageBucket: 'ayucarefinalpro.appspot.com',
  );

}